name: Migration from GitHub Enterprise Cloud

on:
  issue_comment:
    types: [created]

jobs:
  export:
    if: contains(github.event.issue.labels.*.name, 'github-enterprise-cloud')
    uses: ./.github/workflows/shared-github-enterprise-cloud-export.yml
    with:
      runner: ubuntu-latest
      ghes-ssh-host: github.steffenhiller.com
    secrets:
      GHES_ADMIN_USERNAME: test #${{ secrets.GHES_ADMIN_USERNAME }}
      GHES_ADMIN_TOKEN:  test #${{ secrets.GHES_ADMIN_TOKEN }}

  import:
    needs: export
    uses: ./.github/workflows/shared-github-enterprise-server-import.yml
    with:
      user-mappings-path: ../../user-mappings.csv
      user-mappings-source-url: https://github.example.com
    secrets:
      GHEC_ADMIN_TOKEN: test #${{ secrets.GHEC_ADMIN_TOKEN }}
      GHEC_TARGET_ORGANIZATION: test #${{ secrets.GHEC_TARGET_ORGANIZATION }}
