on:
  workflow_call:
    inputs:
      migration-guid:
        default: migration-archive-${{ github.event.issue.number }}
        type: string
      runner:
        default: self-hosted
        type: string
      ghes-ssh-host:
        type: string
        required: true
    secrets:
      GHES_ADMIN_USERNAME:
        required: true
      GHES_ADMIN_TOKEN:
        required: true

jobs:
  export:
    name: Export
    runs-on: ${{ inputs.runner }}

    if: github.event_name == 'issue_comment' &&
      (startsWith(github.event.comment.body, '/run-dry-run-migration') ||
      startsWith(github.event.comment.body, '/run-production-migration'))

    env:
      MIGRATION_GUID: ${{ inputs.migration-guid }}
      GHES_SSH_HOST: ${{ inputs.ghes-ssh-host }}
      GHES_SSH: ssh -p 122 admin@${{ inputs.ghes-ssh-host }}
      GHES_SCP: scp -P 122 
